development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: imageboard_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: imageboard_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: imageboard_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
  host: localhost