development:
  adapter: postgresql
  encoding: unicode
  database: imageboard_development
  pool: 5
  username: toxox
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: imageboard_test
  pool: 5
  username: toxox
  password:
